# Generated by Django 5.1.6 on 2025-10-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_code', models.CharField(max_length=10)),
                ('college_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('merit_rank', models.IntegerField()),
                ('percentile', models.DecimalField(decimal_places=7, max_digits=10)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
